### ISSUE TITLE
Unmet peer dependency: react-native-vector-icons

### ISSUE THREAD

**Issue by kenneth-endare** [WrathChaos/react-native-floating-action-button#1]
When trying to use this library and after installing the necessary peer dependencies, npm still throws an `Unmet peer dependency`-error for `react-native-vector-icons`.

I believe the reason might be the commas instead of dots in the version specification of that peer dependency, right here: https://github.com/WrathChaos/react-native-floating-action-button/blob/master/package.json#L31

**Comment by WrathChaos** [comment]
Hello @kenneth-endare,
Thank you so much for this fix :)
[Release 0.1.13](https://github.com/WrathChaos/react-native-floating-action-button/releases/tag/0.1.13) I fixed the issue and added .npmignore file to reduce file size.
